const CONSTANTS = {
  SOCKET_EVENTS: {
    NEW_MESSAGE: 'NEW_MESSAGE',
    NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
    NEW_MESSAGE_ERROR: 'NEW_MESSAGE_ERROR',
  },
};

module.exports = CONSTANTS;
